---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc
      extension:
        - .es6
        - .js
  fixme:
    enabled: true
ratings:
  paths:
  - "**.es6"
  - "**.js"
exclude_paths:
- tests/
