---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    config: .eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- tests/
