---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config: ./.eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- tests/
